Security & Hardening Guide: New chapter about restricting cron and at
SUSE/doc-sle pull request #1013
Opened 2021-11-12 14:38 UTC by cwickert

… (BSC#1176613, BSC#1176614)

### PR creator: Description

This PR migrates two chapters from the SAP HANA Hardening Guide to the SLE Security & Hardening Guide.

### PR creator: Are there any relevant issues/feature requests?

*[BSC#1176613: Migrate chapter 'Implement cron.allow' from OS Hardening Guide for SAP HANA to SLES Hardening Guide](https://bugzilla.suse.com/show_bug.cgi?id=1176613)
*[BSC#1176614: Migrate chapter 'Implement at.allow' from OS Hardening Guide for SAP HANA to SLES Hardening Guide](https://bugzilla.suse.com/show_bug.cgi?id=1176614)

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2021-11-15 09:33 UTC, jsegitz requested changes

2021-11-15 09:33 UTC, jsegitz commented on xml/security_cron_at.xml
> +   The Linux <systemitem class="daemon">cron</systemitem> system is used to
-Linux, cron is available for many systems

2021-11-15 09:33 UTC, jsegitz commented on xml/security_cron_at.xml
> +    Consider uninstalling the daemon if you don't have valid users instead of
valid use cases

2021-11-15 13:37 UTC, cwickert commented
Thanks for the review, @jsegitz. I've incorporated your feedback, please approve if you are fine with it.

2021-11-15 15:53 UTC, jsegitz approved these changes

2021-11-15 21:47 UTC, cjschroder approved these changes
Looks good, and I am glad you mentioned systemd timers.

2021-11-16 08:03 UTC, cwickert commented
> I am glad you mentioned systemd timers.

Ah, good you mention it. I added a reference to the timer units chapter in 13b5549.

2021-11-16 08:08 UTC, merged