New capability for sudoers.ldap: user negation now works
SUSE/doc-sle pull request #1070
Opened 2022-01-31 20:36 UTC by cjschroder

resolves Jira SLE-21385
This will be backported to SLE 11 SP4, after the changes appears in the maintenance update repo.
See the epic at Jira SLE-20068.

### PR creator: Description

Describe the overall goals of this pull request.

### PR creator: Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2022-02-08 02:08 UTC, Firstyear requested changes

2022-02-08 02:08 UTC, Firstyear commented on xml/security_ldap_install.xml
> +         <command>sudo</command> command, one of its limitations is
I think this should sudoers file not sudo command here. sudoers.ldap replaces/supplements the sudoers / sudoers.d files.

2022-02-08 02:08 UTC, Firstyear commented on xml/security_ldap_install.xml
> +         negation does not work as you might expect in the
"as you might expect" seems like odd language choice for docs. I think it should be "limitations is negation in sudo rules was not available".

2022-02-08 02:08 UTC, Firstyear commented on xml/security_ldap_install.xml
> +    correctly for the <literal>sudoUser</literal> attribute. See
"correctly" I think should be "the same as negation rules in sudoers"

2022-02-08 15:23 UTC, cjschroder commented
Thanks @Firstyear! I just realized this needs an actual sudoers.ldap section. I am marking this as a draft until I add more information.

2022-02-08 23:09 UTC, Firstyear commented
No problem, ping me if you want another review.

2022-02-22 20:20 UTC, cjschroder commented
I'm going to merge and backport as this is now in the update repos, from SLE15SP4 to SLE12SP5. A howto section is in progress.

2022-02-22 20:20 UTC, merged

2022-02-23 18:44 UTC, cjschroder commented
SLE15SP3 c2a01f31a
SLE15SP2 f03e9cd3

https://github.com/SUSE/doc-sle/pull/1090:
SLE15SP1 ac33450ef
SLE15SP0 9e3e55ba9
SLE12SP5 3006164a3