add warning to FIPS chapter that MD5 is unsupported for Samba/CIFS
SUSE/doc-sle pull request #1169
Opened 2022-04-14 16:56 UTC by cjschroder

### PR creator: Description
Add warning to FIPS chapter that MD5 is unsupported for Samba/CIFS. 

### PR creator: Are there any relevant issues/feature requests?

jira-SLE-23133

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2022-04-14 17:28 UTC, cjschroder commented
Here is a PDF for easier reviewing:
[Uploading cha-security-fips_color_draft_en.pdf…]()

2022-04-27 17:25 UTC, denknorr requested changes

2022-04-27 17:29 UTC, cjschroder commented on xml/security_fips.xml
> +   FIPS-compliant network environment, and your clients and servers run in
good point, I will make it 'and you have clients or servers...'

2022-04-27 18:22 UTC, denknorr approved these changes

2022-04-27 18:41 UTC, merged

2022-04-27 19:05 UTC, cjschroder commented
SLE15SP3 37600dd60
SLE15SP2 1d6c35729
SLE15SP1 37431138d
SLE15SP0 61981eff2

2022-04-28 00:38 UTC, cjschroder commented
related: https://github.com/SUSE/doc-sle/pull/1181/