Cockpit rework
SUSE/doc-sle pull request #1235
Opened 2022-05-20 10:02 UTC by lvicoun

### PR creator: Description

Adding a new Cockpit plugin for SLE Micro.

### PR creator: Are there any relevant issues/feature requests?

* SMO-99

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [X] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2022-05-20 11:33 UTC, skazi0 requested changes
Looks good. Minor comments inline.

2022-05-20 11:33 UTC, skazi0 commented on xml/art_admin_slemicro.xml
> +     Reboot</guimenu>. The command <command>transactional-update up</command>
The actual work is done via DBUS API so to be 100% correct I would say something like "The equivalent of `transactional-update up` command is called..."

2022-05-20 11:33 UTC, skazi0 commented on xml/art_admin_slemicro.xml
> +     active. Do not made any changes (install updates, packages, etc.) before
made -> make

2022-05-23 06:02 UTC, skazi0 approved these changes

2022-05-23 10:17 UTC, dariavladykina reviewed
Hi Jana, please see some suggestions. Thanks!

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +     user details view opens and you can edit the user.
```suggestion
     user details view opens, and you can edit the user.
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +     </mediaobject>
Alt text missing?

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +      <term>Manage the user's password</term>
```suggestion
      <term>Manage user's password</term>
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +        particular user from the system.
```suggestion
        By clicking <guimenu>Terminate session</guimenu>, you can log the
        user out of the system.
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +      <term>Manage access of the account</term>
```suggestion
      <term>Manage access to the account</term>
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +        By clicking <guimenu>Force change</guimenu>, the user will have to
```suggestion
        If you click <guimenu>Force change</guimenu>, the user will have to
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +        Click <guimenu>edit</guimenu> to set whether or when the password
```suggestion
        Click <guimenu>Edit</guimenu> to set whether or when the password
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +        You can add a SSH key for passwordless authentication via SSH. Click
```suggestion
        You can add a SSH key for a passwordless authentication via SSH. Click
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro.xml
>   <section xml:id="sec-user-mamagement">
```suggestion
 <section xml:id="sec-user-management">
```

2022-05-23 10:17 UTC, dariavladykina commented on xml/art_admin_slemicro_cockpit.xml
> +        You can lock the account or you can set a date when the account will
```suggestion
        You can lock the account, or you can set a date when the account will
```

2022-05-23 12:40 UTC, merged