Jhalackova pcp container
SUSE/doc-sle pull request #1258
Opened 2022-06-10 14:02 UTC by lvicoun

### PR creator: Description

Adding PCP container description for SLE Micro

### PR creator: Are there any relevant issues/feature requests?

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [ x ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 SP0
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2022-06-13 14:52 UTC, djoreilly requested changes

2022-06-13 14:52 UTC, djoreilly commented on xml/art_admin_slemicro.xml
> +          is a path inside the container to the bind mount on the host. This
`is the path inside the container to the bind mount of the host's root filesystem.`

2022-06-13 14:52 UTC, djoreilly commented on xml/art_admin_slemicro.xml
> +    <section xml:id="sec-config-default">
I would remove this section. I'm not exactly sure how you would add metrics after the auto generation is done on container start. Anyway I don't see the need to manually add metrics.

2022-06-16 14:32 UTC, lvicoun commented on xml/art_admin_slemicro.xml
> +<screen>&prompt.root;pminfo</screen>
Or mention that the command should run inside the container?

2022-06-17 12:56 UTC, djoreilly approved these changes
lgtm - thanks!

2022-06-20 12:06 UTC, dariavladykina reviewed
Hi Jana, please take a look at some suggestions. Thanks!

2022-06-20 12:06 UTC, dariavladykina commented on xml/art_admin_slemicro.xml
> +     the following configuraiton files:
```suggestion
     the following configuration files:
```

2022-06-20 12:06 UTC, dariavladykina commented on xml/art_admin_slemicro.xml
> +# Uncomment one of the lines below to enable/disable compression behaviour
```suggestion
# Uncomment one of the lines below to enable/disable compression behavior
```

2022-06-20 12:06 UTC, dariavladykina commented on xml/art_admin_slemicro.xml
> +fault -v 100Mb
```suggestion
LOCALHOSTNAME   y   n   PCP_ARCHIVE_DIR/LOCALHOSTNAME   -r -T24h10m -c config.default -v 100Mb
```

2022-06-20 14:31 UTC, merged