Add info about VNC+Wayland compatibility (bsc#1202038)
SUSE/doc-sle pull request #1368
Opened 2022-09-28 13:09 UTC by ismaell

### PR creator: Description

Warn users about Wayland incompatibility with VNC sessions.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1202038

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2
  - [x] SLE 15 SP1
  - [x] SLE 15 SP0
- SLE 12
  - [x] SLE 12 SP5
  - [x] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2022-11-02 17:30 UTC, taroth21 commented
@ismaell : Many thanks for opening the PR and sorry for reviewing only now! I would have a few minor corrections for the PR (language and style issues). I could not push them from my local branch (based on your PR) back to your fork directly because I lack permissions. Do you want me to make code suggestions instead?

2022-11-02 18:00 UTC, ismaell commented
Sure, suggestions would also help me improve.

2022-11-04 08:32 UTC, taroth21 requested changes
Hi, I have a few minor correction suggestions (language and style-related), otherwise I'm fine with the addition. Many thanks!

2022-11-04 08:32 UTC, taroth21 commented on xml/vnc.xml
> +    <filename>/etc/gdm/custom.conf</filename> configuration file.
```suggestion
   For <package>gdm</package>, edit <filename>/etc/gdm/custom.conf</filename>.
   In the <literal>[daemon]</literal> section, add <literal>WaylandEnable=false</literal>
   to the configuration file.
```

2022-11-04 08:32 UTC, taroth21 commented on xml/vnc.xml
> +    When logging in, the user must choose a X11-compatible session as well.
```suggestion
    When logging in, the user must choose an X11-compatible session as well.
```

2022-11-04 08:32 UTC, taroth21 commented on xml/vnc.xml
> +    If you wish to remove the Wayland option for GNOME, you can remove and lock
```suggestion
    If you wish to remove the Wayland option for &gnome;, you can remove and lock
```

2022-11-04 08:32 UTC, taroth21 commented on xml/vnc.xml
> +    <filename>/etc/gdm/custom.conf</filename> configuration file.
It is easier to follow the instructions when you first mention which file and which section to edit, and only then mention the parameter settings.

2022-11-04 08:32 UTC, taroth21 commented on xml/vnc.xml
> +    The Remote Admininstration (VNC) feature relies on X11 and may result in an
```suggestion
    The Remote Administration (VNC) feature relies on X11 and may result in an
```

2022-11-04 16:55 UTC, taroth21 approved these changes

2022-11-04 16:57 UTC, merged

2022-11-04 16:58 UTC, taroth21 commented
Thank you, @ismaell! I have merged this to `main` now and will take care of backporting the changes to the other branches next week.

2022-11-08 16:57 UTC, taroth21 commented
@ismaell : All backports are done now, the changes will be published on documentation.suse.com with the next weekly SLE updates.

2022-11-08 16:59 UTC, ismaell commented
Thanks.