Correct SELinux Documentation for 15 SP5/SP4 (bsc#1208592)
SUSE/doc-sle pull request #1453
Opened 2023-03-03 14:46 UTC by taroth21

### PR creator: Description

Add corrections suggested by @jsegitz (correct `restorecon`  command and remove (unneeded) `enforcing=0` boot parameter for permissive mode.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1208592
* jsc#DOCTEAM-906

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2023-03-03 14:52 UTC, taroth21 commented
@jsegitz : PDF output of the changes:
[cha-selinux_2023-03-03.pdf, sections 43.5 and 43.6](https://github.com/SUSE/doc-sle/files/10883039/cha-selinux_2023-03-03.pdf)

Please compare to 

- https://documentation.suse.com/sles/15-SP4/single-html/SLES-security/#sec-selinux-mode-permissive
- https://documentation.suse.com/sles/15-SP4/single-html/SLES-security/#sec-selinux-mode-enforcing

2023-03-03 14:58 UTC, jsegitz requested changes

2023-03-03 14:58 UTC, jsegitz commented on xml/selinux.xml
> +   and access will be denied based on policy rules.
Just editing /etc/selinux/config is enough. Please remove the part about modifying the grub config

2023-03-03 15:06 UTC, jsegitz approved these changes

2023-03-06 08:51 UTC, dariavladykina reviewed
LGTM, thanks!

2023-03-06 10:31 UTC, merged