added the correct service name
SUSE/doc-sle pull request #1481
Opened 2023-04-06 13:26 UTC by Amrita42

### PR creator: Description

The current command syntax for the sfcbd daemon , is not correct and needs a prefix of 
`sblim`

### PR creator: Are there any relevant issues/feature requests?

[https://jira.suse.com/browse/DOCTEAM-699](DOCTEAM-699)

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [ x] SLE 15 SP4/openSUSE Leap 15.4
  - [ x] SLE 15 SP3/openSUSE Leap 15.3
  - [x ] SLE 15 SP2/openSUSE Leap 15.2
  - [ x] SLE 15 SP1
- SLE 12
  - [ x] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2023-04-11 09:24 UTC, tbazant requested changes
LG, just minor improvements

2023-04-11 09:24 UTC, tbazant commented on xml/adm_wbem.xml
> +         Enter <command>systemctl start sblim-sfcb</command> as &rootuser; in the
```suggestion
         Enter <command>systemctl start sblim-sfcb.service</command> as &rootuser; in the
```

2023-04-11 09:24 UTC, tbazant commented on xml/adm_wbem.xml
> +         Enter <command>systemctl stop sblim-sfcb</command> as &rootuser; in the
```suggestion
         Enter <command>systemctl stop sblim-sfcb.service</command> as &rootuser; in the
```

2023-04-11 09:24 UTC, tbazant commented on xml/adm_wbem.xml
> +         Enter <command>systemctl status sblim-sfcb</command>as &rootuser; in the
```suggestion
         Enter <command>systemctl status sblim-sfcb.service</command> as &rootuser; in the
```

2023-04-12 07:20 UTC, tbazant commented on xml/adm_wbem.xml
> +         Enter <command>systemctl status sblim-sfcb.service</command>as &rootuser; in the
```suggestion
         Enter <command>systemctl status sblim-sfcb.service</command> as &rootuser; in the
```

2023-04-12 08:03 UTC, dariavladykina approved these changes
No findings, thanks

2023-04-12 12:04 UTC, merged