Added extensive informatiopnfor Python 3 module (from RN)
SUSE/doc-sle pull request #1563
Opened 2023-07-28 15:52 UTC by fsundermeyer

fixes PED-4724

We need to update lifecycle information and module content on the Python 3 module description 

Backport required to
  - [ ] SLE 15 SP4/openSUSE Leap 15.5

2023-07-28 17:17 UTC, dirkmueller commented on xml/art_modules.xml
> +    This module contains version 3.11 of selected Python 3 packages.
```suggestion
This module provides Python 3.11 interpreter (including setuptools, wheel, and pypi support) and many additional maintained python 3.11 modules. 
````

2023-07-28 17:19 UTC, dirkmueller commented on xml/art_modules.xml
> +   </para>
suggest to delete all of that. the release notes explain that already and it doesn't make sense to explain in the paragraph about the python3 module something that is not in the python3 module.

2023-07-28 17:19 UTC, dirkmueller commented on xml/art_modules.xml
> +   </para>
suggest to move this to the end of this section

2023-07-28 17:22 UTC, dirkmueller commented on xml/art_modules.xml
> +    each service Pack (if applicable) and will be supported for 18 months.
```suggestion
    The Python 3.11 and the contained python 3.11 modules are supported at least until end of December 2027. The Python 3.11 modules might be updated at the next service pack (if compatible and when needed).
```

2023-07-28 17:22 UTC, dirkmueller commented on xml/art_modules.xml
> +      <emphasis role="bold">Lifecycle:</emphasis> December 2027 (Python 3.11)
This is tricky, as the lifecycle of the SP4/SP5 module is the underlying SP lifecycle. it just happens to align here.

2023-07-28 17:23 UTC, dirkmueller requested changes
Please see inline comments

2023-07-31 16:24 UTC, fsundermeyer commented
Thank you, @dirkmueller !

2023-07-31 19:36 UTC, dirkmueller approved these changes

2023-08-01 10:40 UTC, dariavladykina reviewed
Hi, please see some suggestions here. Thanks!

2023-08-01 10:40 UTC, dariavladykina commented on xml/art_modules.xml
> +    compatible and when needed).
```suggestion
    and pypi support) and many additional maintained Python 3.11 modules. It has
    a different lifecycle than &productname; itself. The Python 3.11 and the
    contained Python 3.11 modules are supported at least until the end of December
    2027. The Python 3.11 modules might be updated with the next service pack (if
    compatible and when needed).
```

2023-08-01 10:40 UTC, dariavladykina commented on xml/art_modules.xml
> +    Python packages and they can coexist within the same system without
```suggestion
    Python packages, and they can coexist in the same system without
```

2023-08-01 10:40 UTC, dariavladykina commented on xml/art_modules.xml
> +    or 3.10 should run without or with only minimal changes in 3.11.
```suggestion
    In &productname; &productnumber;, the Python 3 module ships with Python 3.11.
    Python 3.11 is compatible with versions 3.10 and 3.9. The code written in 3.9
    or 3.10 should run without changes or only with minimal changes in 3.11.
```

2023-08-01 10:40 UTC, dariavladykina commented on xml/art_modules.xml
> +      <emphasis role="bold">Lifecycle:</emphasis> December 31st 2027
```suggestion
      <emphasis role="bold">Lifecycle:</emphasis> 31 Dec 2027
```

2023-08-08 07:59 UTC, merged