Btrfs zstd
SUSE/doc-sle pull request #632
Opened 2020-08-02 22:42 UTC by ddiss

zstd documentation is missing from the Btrfs compression section.
It's can be used with SLES 15sp1+.

2020-08-03 12:06 UTC, ddiss commented
Hmm, I just checked (with openSUSE 15.2) and found that zstd compression isn't supported by GRUB (it's supported upstream via http://git.savannah.gnu.org/cgit/grub.git/commit/?id=461f1d8af1820623dfc1e1e62c6f9f24c33793ba), so zstd will also need to be covered by the existing `Note: GRUB 2 and LZO Compressed Root` caveat.

2020-08-19 09:15 UTC, ddiss commented
Ping - any feedback here?

2020-08-25 14:22 UTC, taroth21 requested changes
@ddiss : David, many thanks - just a typo fix from my side.

2020-08-25 14:22 UTC, taroth21 commented on xml/storage_filesystems.xml
> +     preformance close to lzo and compression ratios similar to zlib.
```suggestion
     performance close to lzo and compression ratios similar to zlib.
```

2020-08-25 14:34 UTC, taroth21 commented
@ddiss : It's a bit hard to follow to which product version this fix applies... (PR description mentions 15SP1+ but then https://github.com/SUSE/doc-sle/pull/632/commits/bca52d703ae4c mentions it is not supported for 15SP2 out of the box), that's probably why Stefan flagged it with 'on hold: merge later' and 'SLE15SP3' only. 

Could you clarify please?

FYI: If the fix applies to SLE15SP3 only, it is on hold for now, we will merge the SP3-only changes into master when we start to update the product documentation for SP3 (~Nov. 2020).

2020-08-25 15:28 UTC, ddiss commented on xml/storage_filesystems.xml
> +     preformance close to lzo and compression ratios similar to zlib.
Fixed, thanks

2020-08-25 15:41 UTC, ddiss commented
Thanks for the feedback Tanja...

> @ddiss : It's a bit hard to follow to which product version this fix applies... (PR description mentions 15SP1+ but then bca52d7 mentions it is not supported for 15SP2 out of the box), that's probably why Stefan flagged it with 'on hold: merge later' and 'SLE15SP3' only.
> 
> Could you clarify please?

This documentation applies to SLES15-SP1 and later. The GRUB commit explicitly mentions 15SP2 because that's where I checked it; prior releases are expected to also lack bootloader zstd support.

2020-08-27 12:13 UTC, taroth21 approved these changes

2020-08-27 12:15 UTC, merged

2020-08-27 14:07 UTC, taroth21 commented
@ddiss :+1: Merged and backported to the following branches:

- maintenance/SLE15SP2
- maintenance/SLE15SP1