Remove locale step on jeos-firstboot
SUSE/doc-sle pull request #654
Opened 2020-09-16 15:19 UTC by gmoro

Add new section about locale configuration

### Description

Add new section for local configuration and remove the now obsolete (removed) step of jeos-firstboot warning about that

Test build ran on travis is green

### Are there any relevant issues/feature requests?

https://jira.suse.com/browse/PM-2100

### Is this feature exclusive to SLE 15 SP3 (or Leap 15.3)?

We are currently **only merging documentation relevant for SLE 15 SP2**
(and Leap 15.2) or lower.

- [ x] This PR only applies to SLE 15 SP3 or higher
- [ ] This PR applies to older releases as well.

### Are backports required?

- [ ] To maintenance/SLE15SP2
- [ ] To maintenance/SLE15SP1
- [ ] To maintenance/SLE15SP0
- [ ] To maintenance/SLE12SP5
- [ ] To maintenance/SLE12SP4
- [ ] To maintenance/SLE12SP3
- [ ] To maintenance/SLE12SP2

2020-09-18 08:35 UTC, taroth21 commented
@gmoro : Thank you for the PR! I have assigned it to Liam Proven for language and style review. 
Please note that we will merge this PR only after we have started to update the docs for SLE 15 SP3.

2020-09-18 08:42 UTC, gmoro commented
> @gmoro : Thank you for the PR! I have assigned it to Liam Proven for language and style review.
> Please note that we will merge this PR only after we have started to update the docs for SLE 15 SP3.

hi @taroth21, thanks for that.

2020-09-19 14:27 UTC, dmpop commented
Apologies for missing this PR, but Vincent mentioned me by name, so I went ahead and fixed this in https://github.com/SUSE/doc-sle/commit/a5b69fb6e37418a79a34e714eb5ad89b65dbac9f

I think we can close this PR.

2020-09-21 11:37 UTC, lproven requested changes

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
>       After &jeos; has been successfully installed and registered, we highly
```suggestion
     After &jeos; has been successfully installed and registered, we strongly
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
>       recommend to install the latest available online updates.
```suggestion
     recommend installing the latest available online updates.
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    completed, using the instructions provided below.
```suggestion
    The JeOS image comes with only one locale: English (<literal>en_US</literal>). You can
    install and select a different system locale, if desired, after setup has
    completed, using the instructions provided below.
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    Install glibc-locale:
```suggestion
    Install <literal>glibc-locale</literal>:
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    Use localectl to change to the locale desired, for example, to change
```suggestion
    Use <command>localectl</command> to change to the locale desired; for example, to change
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    the main system language to German use:
```suggestion
    the main system language to German, use:
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    For a complete list of the locale codes available use:
```suggestion
    For a complete list of the locale codes available, use:
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    For more information on language settings and how to use it with YaST
```suggestion
    For more information on language settings and how to use them with &yast;
```

2020-09-21 11:37 UTC, lproven commented on xml/art_jeos_quickstart.xml
> +    in SLE please check <xref linkend="cha-yast-lang"/>
```suggestion
    in &sle;, refer to <xref linkend="cha-yast-lang"/>
```

2020-09-21 14:58 UTC, dmpop commented
I'm closing the PR, as the issue it addresses has already been fixed. Thank you for your contribution, @gmoro !

2020-09-21 14:58 UTC, closed without merging