Added a new chapter on preparing the VM host
SUSE/doc-sle pull request #712
Opened 2020-11-20 12:55 UTC by tbazant

### Description

VM guests need storage and network resource provided by the VM host. This new chapter consolidates existing content and moves it into the libvirt chapter right before guest installation.

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ---------- 
| [x] 15 SP3  | (`master` only)   
| [ ] 15 SP2  | [ ] 
| [ ] 15 SP1  | [ ] 
| [ ] 15 SP0  | [ ] 

| Code 12     | Backport Done
| ----------  | ---------- 
| [ ] 12 SP5  | [ ] 
| [ ] 12 SP4  | [ ] 
| [ ] 12 SP3  | [ ] 
| [ ] 12 SP2  | [ ]

2020-11-20 18:32 UTC, lproven requested changes

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        and end IP address range of assignable addresses.
```suggestion
        and end IP addresses of a range to be made assignable.
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +      <title>NAT Based Network</title>
```suggestion
      <title>NAT-Based Network</title>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +       it is available on &vmhost;. In the absence of &vmhost; networking, it
```suggestion
       it is available on the &vmhost;. In the absence of &vmhost; networking, it
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         When defining a new network with a &lt;forward&gt; mode of "nat" or
```suggestion
         When defining a new network with a &lt;forward&gt; mode of <literal>"nat"</literal> or
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         "route" (or an isolated network with no &lt;forward&gt; element),
```suggestion
         <literal>"route"</literal> (or an isolated network with no &lt;forward&gt; element),
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         most common modes are "nat" (default, network address translation),
```suggestion
         most common modes are <literal>"nat"</literal> (Network Address Translation, the default),
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         "route" (direct forwarding to the physical network, no address
```suggestion
         <literal>"route"</literal> (direct forwarding to the physical network, no address
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         translation), and "bridge" (network bridge configured outside of
```suggestion
         translation), and <literal>"bridge"<literal> (network bridge configured outside of
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +         <literal>end</literal> attribute.
```suggestion
         <literal>end</literal> attributes.
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +    To be able to access CD/DVD ISO images on the &vmhost; from remote, they
From remote what? From remote hosts, or remote clients, or remote machines in general?

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +    <title>Starting, Stopping and Deleting Pools</title>
```suggestion
    <title>Starting, Stopping, and Deleting Pools</title>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +    functions like starting, stopping and deleting pools and volume management.
```suggestion
    functions such as starting, stopping, and deleting pools, and volume management.
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +     Volumes can only be listed per pool by default. To list all volumes from a
```suggestion
     By default, volumes can only be listed per pool. To list all volumes from a
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +     Use the <command>virsh</command> pool subcommands to start, stop or delete
```suggestion
     Use the <command>virsh</command> pool subcommands to start, stop, or delete
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +       Format of the volume. &suse; currently supports <literal>raw</literal>,
```suggestion
       Format of the volume. &suse; currently supports <literal>raw</literal>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +       Format of the volume. &suse; currently supports <literal>raw</literal>,
I think we don't need an Oxford comma when there are only 2 items.

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +       Optional parameter. By default <command>virsh </command>creates a sparse
```suggestion
       Optional parameter. By default, <command>virsh</command> creates a sparse
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>dir</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>dir</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>disk</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>disk</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>fs</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>fs</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>iscsi</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>iscsi</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>logical</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>logical</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>mpath</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>mpath</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        <term><emphasis role="bold">Type</emphasis><guimenu>scsi</guimenu></term>
```suggestion
        <term><emphasis role="bold">Type</emphasis> <guimenu>scsi</guimenu></term>
```

2020-11-20 18:32 UTC, lproven commented on xml/libvirt_host.xml
> +        possible when operating from remote.
Again: when operating from **a** remote _what_?

If this is not know, then I suggest: 

... is not possible when operating remotely.

2020-11-25 15:44 UTC, tbazant reviewed
Added a few suggestions as hinted by @lproven

2020-11-25 15:44 UTC, tbazant commented on xml/libvirt_host.xml
> +        real Ethernet device, use <guimenu>Statically assigned IP
```suggestion
        real network device, use <guimenu>Statically assigned IP
```

2020-11-25 15:44 UTC, tbazant commented on xml/libvirt_host.xml
> +    To be able to access CD/DVD ISO images on the &vmhost; from remote, they
```suggestion
    To be able to access CD/DVD ISO images on the &vmhost; from remote clients, they
```

2020-11-25 15:44 UTC, tbazant commented on xml/libvirt_host.xml
> +        possible when operating from remote.
```suggestion
        possible when operating remotely.
```

2020-11-26 10:47 UTC, aginies approved these changes
Sounds ok, i read quickly the end, as the changes are mostly on the top.

2020-11-27 08:30 UTC, merged