Update Tuning Guide to sentence case (WIP)
SUSE/doc-sle pull request #740
Opened 2021-01-05 15:31 UTC by sknorr

### Description

* The new capitalization rules are documented at https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization, read carefully
* This is the result of an automatic conversion and will most likely need further adjustments
  * Make sure to review the entire diff
  * Entity files have not been changed and need to be updated manually
  * Some product/project names may have been inadvertently changed to the wrong capitalization
  * Some titles may have been missed, either because they're split across multiple source lines or because of improper markup
* Update the conversion commit and remove the (WIP) from the commit message before merging
* This is the fifth PR in a series of 14 PRs

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ---------- 
| [x] 15 SP3  | (`master` only)   
| [ ] 15 SP2  | [ ] 
| [ ] 15 SP1  | [ ] 
| [ ] 15 SP0  | [ ] 

| Code 12     | Backport Done
| ----------  | ---------- 
| [ ] 12 SP5  | [ ] 
| [ ] 12 SP4  | [ ] 
| [ ] 12 SP3  | [ ] 
| [ ] 12 SP2  | [ ]

2021-01-05 19:06 UTC, cjschroder requested changes
I am also submitting a PR to this branch with corrections.

2021-01-05 19:06 UTC, cjschroder commented on xml/utilities.xml
> +    <title><command>vmstat</command> Output on a lightly used machine</title>
Not sure if Output should be capitalized.

2021-01-05 19:06 UTC, cjschroder commented on xml/utilities.xml
> +    <title><command>vmstat</command> Output on a heavily used machine (CPU bound)</title>
Not sure if Output should be capitalized.

2021-01-05 20:42 UTC, cjschroder commented
This is still WIP, I will re-check tomorrow after studying the style guide again.

2021-01-07 15:48 UTC, cjschroder approved these changes

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_kexec.xml
> +       <term>Secure file transfer protocol (sftp)</term>
```suggestion
       <term>Secure File Transfer Protocol (SFTP)</term>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_kexec.xml
> +       <term>Secure shell protocol (ssh)</term>
```suggestion
      <term>Secure Shell protocol (SSH)</term>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_kprobes.xml
> +   <title>How to switch all kernel probes on or off</title>
```suggestion
   <title>Globally enabling/disabling kernel probes</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_memory.xml
> +  <title>Non-uniform memory access (NUMA)</title>
```suggestion
  <title>Non-Uniform Memory Access (NUMA)</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_memory.xml
> +  <title>Non-uniform memory access (NUMA)</title>
```suggestion
  <title>Non-Uniform Memory Access (NUMA)</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_network.xml
> +   <title>Side-effects of tuning network variables</title>
```suggestion
    <title>Side effects of tuning network variables</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_numactl.xml
> + <title>Automatic non-uniform memory access (NUMA) balancing</title>
```suggestion
 <title>Automatic Non-Uniform Memory Access (NUMA) balancing</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_perf.xml
> + <title>Hardware-based performance monitoring with perf</title>
```suggestion
 <title>Hardware-based performance monitoring with Perf</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_perf.xml
> +  <title>Installing perf</title>
```suggestion
  <title>Installing Perf</title>
```

2021-01-07 17:38 UTC, sknorr commented on xml/tuning_systemd_coredump.xml
> +   <title>Creating a core dump with vim</title>
```suggestion
   <title>Creating a core dump with Vim</title>
```

2021-01-07 17:44 UTC, merged

2021-01-07 17:44 UTC, sknorr commented
Thanks Carla!

2021-01-07 19:43 UTC, cjschroder commented
Good catches, thanks Stefan. I resolved some merge conflicts and merged to master https://github.com/SUSE/doc-sle/commit/57978f5cc7d1d80e152320234652d7b0b181327a
But there are still some errors, I will fix them Monday.