Tbazant virt guide improvements bsc#1179241
SUSE/doc-sle pull request #770
Opened 2021-02-25 11:05 UTC by tbazant

### Description

This update tries to include multiple unrelated fixes to the virt guides

### Are there any relevant issues/feature requests?

* bsc#1179241

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [x] 15 SP3  | *(no backport necessary)*
| [x] 15 SP2  | [ ]
| [x] 15 SP1  | [ ]
| [x] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [ ] 12 SP5  | [ ]
| [ ] 12 SP4  | [ ]
| [ ] 12 SP3  | [ ]
| [ ] 12 SP2  | [ ]

2021-02-25 14:00 UTC, tbazant commented on xml/vt_scenarios.xml
> +     VM should not share network, storage, or network Hardware.
```suggestion
     VM should not share network, storage, or network hardware.
```

2021-03-03 16:16 UTC, aginies requested changes

2021-03-03 16:16 UTC, aginies commented on xml/qemu_overview.xml
> +  </listitem>
we only provide the matching qemu arch CPU type on SLE. Which means: only qemu-system-x86_64 on x86_64 etc.... so this should be removed.

2021-03-03 16:16 UTC, aginies commented on xml/vt_scenarios.xml
> +     KSM should be avoided.
link to "xml id : gloss-vt-acronym-ksm"  would be nice here

2021-03-08 08:04 UTC, tbazant reviewed
Fixed 2 issues

2021-03-08 08:04 UTC, tbazant commented on xml/qemu_overview.xml
> +  </listitem>
```suggestion
<!-- 2021-03-08 tbazant -arch not part of SLE
  <listitem>
   <para>
    <command>qemu-system-arm</command>
   </para>
  </listitem>
  -->
```

2021-03-08 08:04 UTC, tbazant commented on xml/vt_scenarios.xml
> +     KSM should be avoided.
```suggestion
     KSM should be avoided. For more details on KSM, refer to
     <xref linkend="gloss-vt-acronym-ksm"/>.
```

2021-03-08 08:47 UTC, merged