Added chapter on TPM emulator (jsc#SLE-17527)
SUSE/doc-sle pull request #775
Opened 2021-03-12 13:46 UTC by tbazant

### Description

Added a new chapter on software TPM emulator

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-17527

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [x] 15 SP3  | *(no backport necessary)*
| [ ] 15 SP2  | [ ]
| [ ] 15 SP1  | [ ]
| [ ] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [ ] 12 SP5  | [ ]
| [ ] 12 SP4  | [ ]
| [ ] 12 SP3  | [ ]
| [ ] 12 SP2  | [ ]

2021-03-12 14:53 UTC, lproven requested changes

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   For developers who use TMP to develop security features, a software TPM emulator is a convenient solution.
```suggestion
   For developers who use the TPM to develop security features, a software TPM emulator is a convenient solution.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   Trusted Platform Module (TPM) is a cryptoprocessor that secures hardware by using cryptographic keys.
```suggestion
   The Trusted Platform Module (TPM) is a cryptoprocessor that secures hardware using cryptographic keys.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   Also, it is simple to switch between versions TPM 1.2 and TPM 2.0.
```suggestion
   Also, it is simple to switch between TPM versions 1.2 and 2.0.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +  <title>Using swtpm with &qemu;</title>
Should we use a [command] tag around this? I see from the next paragraph that it **is** a command.

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +    swtpm provides three types of interface: socket, chardev, and cuse.
Would [literal] tags around these make it clearer?

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   &libvirt; will start swtpm for the guest automatically, you do not need to start it manually in advance.
```suggestion
   &libvirt; will start swtpm for the guest automatically; you do not need to start it manually in advance.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   The corresponding permall file will be created in <filename>/var/lib/libvirt/swtpm/<replaceable>VM_UUID</replaceable></filename>.
```suggestion
   The corresponding <filename>permall</filename> file will be created in <filename>/var/lib/libvirt/swtpm/<replaceable>VM_UUID</replaceable></filename>.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +     Details about <package>swtpm</package> usage are in its manual page <command>man 8 swtpm</command>.
```suggestion
     Details about <package>swtpm</package> usage are in its manual page: type <command>man 8 swtpm</command>.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +     Thorough insight into TPM is at the wiki page <link xlink:href="https://en.wikipedia.org/wiki/Trusted_Platform_Module"/>.
```suggestion
     Wikipedia offers a thorough description of the TPM at the page <link xlink:href="https://en.wikipedia.org/wiki/Trusted_Platform_Module"/>.
```

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +     Thorough insight into TPM is at the wiki page <link xlink:href="https://en.wikipedia.org/wiki/Trusted_Platform_Module"/>.
"Wiki" is a generic term and I think we should say _which_ wiki.

2021-03-12 14:53 UTC, lproven commented on xml/vt_qemu_tpm.xml
> +   If the guest uses the OVMF firmware, it will measure components with TPM.
I did not know this abbreviation, so perhaps other readers may not. It stands for Open Virtual Machine Firmware: http://www.linux-kvm.org/downloads/lersek/ovmf-whitepaper-c770f8c.txt

It is an implentation of UEFI for VMs, as opposed to the legacy BIOS. Should we mention this?

2021-03-12 16:12 UTC, jfehlig reviewed
I'm not a TPM expert, but the libvirt and qemu usage LGTM.

2021-03-15 07:55 UTC, tbazant reviewed
Few suggestions

2021-03-15 07:55 UTC, tbazant commented on xml/vt_qemu_tpm.xml
> +  <title>Using swtpm with &qemu;</title>
```suggestion
  <title>Using <command>swtpm</command> with &qemu;</title>
```

2021-03-15 07:55 UTC, tbazant commented on xml/vt_qemu_tpm.xml
> +    swtpm provides three types of interface: socket, chardev, and cuse.
```suggestion
    <command>swtpm</command> provides three types of interface: <literal>socket</literal>, <literal>chardev</literal>, and <literal>cuse</literal>.
```

2021-03-15 07:55 UTC, tbazant commented on xml/vt_qemu_tpm.xml
> +     Details about <package>swtpm</package> usage are in its manual page <command>man 8 swtpm</command>.
no, brackets are better

2021-03-15 07:55 UTC, tbazant commented on xml/vt_qemu_tpm.xml
> +     Details about <package>swtpm</package> usage are in its manual page <command>man 8 swtpm</command>.
```suggestion
     Details about <package>swtpm</package> usage are in its manual page (<command>man 8 swtpm</command>).
```

2021-03-15 07:55 UTC, tbazant commented on xml/vt_qemu_tpm.xml
> +   If the guest uses the OVMF firmware, it will measure components with TPM.
```suggestion
   If the guest uses the Open Virtual Machine Firmware (OVMF), it will measure components with TPM.
```

2021-03-15 08:22 UTC, merged