Enable custom repo attached to a product (jsc#DOCTEAM-57)
SUSE/doc-sle pull request #806
Opened 2021-04-07 10:19 UTC by tbazant

### Description

User needs to enable newly added custom repos attached to a product.

### Are there any relevant issues/feature requests?

* jsc#DOCTEAM-57

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [x] 15 SP3  | *(no backport necessary)*
| [x] 15 SP2  | [ ]
| [x] 15 SP1  | [ ]
| [x] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [ ] 12 SP5  | [ ]
| [ ] 12 SP4  | [ ]
| [ ] 12 SP3  | [ ]
| [ ] 12 SP2  | [ ]

2021-04-07 10:21 UTC, digitaltom approved these changes

2021-04-07 10:29 UTC, felixsch approved these changes

2021-04-07 13:09 UTC, tbazant commented on xml/rmt_mirroring.xml
> +      When custom repositories are attached to a product, clients registering to that product will have such repo added in a disabled state.
```suggestion
      When custom repositories are attached to a product, clients registering to that product will have such repository added in a disabled state.
```

2021-04-08 14:50 UTC, lproven requested changes

2021-04-08 14:50 UTC, lproven commented on xml/rmt_mirroring.xml
> +      To enable the repository, find its ID with the <command>zypper lr</command> and run:
```suggestion
      To enable the repository, find its ID with the command <command>zypper lr</command> and run:
```

2021-04-12 08:04 UTC, merged