AutoYaST: add missing elements
SUSE/doc-sle pull request #824
Opened 2021-04-20 21:02 UTC by imobachgs

### Description

This PR adds documentation for some elements that were missing in the AutoYaST guide. I have tried to organize them in different commits, so it is easy to review and even backport them.

* 1a9e644: add "update_nvram" (**new in SLE 15 SP3**).
* 197257f: add "virt_bridge_proposal" (**new in SLE 15 SP3**).
* 797c3aa: explaining that it is possible to use `t` instead of `config:type` (**new in SLE 15 SP3**).
* 309b4b0: drop the `domain` element from an example. It was deprecated a few releases ago, but we forgot to update the example. **Backport to SP2 if possible**.
* 73d5d16 and 8d30ce6: the introduction of the networking section was somehow confusing. Some elements were not documented while others were just mentioned in the examples. I am not 100% happy with the new text, but I think it is a step in the right direction. **Backport to SP2 if possible**.

If needed, I can take care of creating the PRs with the changes to backport.

Thanks!

### Are there any relevant issues/feature requests?

* [bsc#1183606](https://bugzilla.suse.com/show_bug.cgi?id=1183606)

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [ ] 15 SP3  | *(no backport necessary)*
| [ ] 15 SP2  | [ ]
| [ ] 15 SP1  | [ ]
| [ ] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [ ] 12 SP5  | [ ]
| [ ] 12 SP4  | [ ]
| [ ] 12 SP3  | [ ]
| [ ] 12 SP2  | [ ]

2021-04-21 14:40 UTC, cjschroder requested changes
Hi Imobach, thank you for the excellent PR! I found a few typos, nothing exciting. Please fix and I will merge.

2021-04-21 14:40 UTC, cjschroder commented on xml/ay_bootloader.xml
> +        in the firmware. This is the desiderable behavior unless you want to preserve some
desiderable > desirable

2021-04-21 14:40 UTC, cjschroder commented on xml/ay_control_file.xml
> +    <title>Using emacs as an XML editor</title>
Is this the correct title? Not sure what this has to do with emacs.

2021-04-21 14:40 UTC, cjschroder commented on xml/ay_control_file.xml
> +     <phrase os="osuse">15.3</phrase>, it is posible to use the attribute
posible > possible

2021-04-21 14:40 UTC, cjschroder commented on xml/ay_control_file.xml
> +     Starting with in &productname; <phrase os="sles;sled">15 SP3</phrase>
Starting with in > Starting with

2021-04-21 14:40 UTC, cjschroder commented on xml/ay_networking.xml
> +        that, it shows a warning whose timeout is controlled by this element. If it is set to
In that > In that case

Is the timeout value in seconds?

2021-04-21 14:42 UTC, cjschroder commented
If needed, I can take care of creating the PRs with the changes to backport.

I will backport, no worries. Thanks again, very much appreciate your maintaining the AY Guide.

2021-04-22 10:13 UTC, imobachgs commented
Hi @cjschroder. I have fixed those issues. Thanks for the review!

2021-04-22 13:56 UTC, cjschroder commented
Thank you @imobachgs!

2021-04-22 13:56 UTC, merged