Improvements for ARM architecture (bsc#1182738)
SUSE/doc-sle pull request #828
Opened 2021-04-27 10:27 UTC by tbazant

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#1182738
* jsc#DOCTEAM-37

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [x] 15 SP3  | *(no backport necessary)*
| [x] 15 SP2  | [ ]
| [x] 15 SP1  | [ ]
| [x] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [ ] 12 SP5  | [ ]
| [ ] 12 SP4  | [ ]
| [ ] 12 SP3  | [ ]
| [ ] 12 SP2  | [ ]

2021-04-27 15:12 UTC, lproven requested changes

2021-04-27 15:12 UTC, lproven commented on xml/qemu_running_vms_qemukvm.xml
> +    a BIOS image file with the <option>-bios</option> option. For example:
```suggestion
    a firmware image file with the <option>-bios</option> option. For example:
```

2021-04-27 15:12 UTC, lproven commented on xml/qemu_running_vms_qemukvm.xml
> +    a BIOS image file with the <option>-bios</option> option. For example:
Whatever the QEMU option is, UEFI is not a BIOS.

2021-04-28 15:00 UTC, lproven approved these changes

2021-05-03 15:04 UTC, aginies approved these changes

2021-05-05 11:35 UTC, merged