Update AY Guide for SLE Micro with additional profiling
SUSE/doc-sle pull request #864
Opened 2021-05-24 17:41 UTC by cjschroder

re BSC# 1185835, profiled second stage options not supported
in SLE Micro. No AY second-stage options are supported.

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(if applicable to 15 SP4 _only_ -- do not merge yet!)*
  - [x ] SLE 15 SP3/openSUSE Leap 15.3 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2021-05-24 21:33 UTC, imobachgs commented
Thanks Carla! In general, it looks good. However, I have spotted other places to change.

* **9.2.3 Booting via PXE over the network** mentions the second stage. I think that just removing the last part of the paragraph should be enough:

*If you install via PXE, the installation will run in an endless loop. This happens because after the first reboot, the machine performs the PXE boot again and restarts the installation instead of booting from the hard disk ~~for the second stage of the installation~~.*

* The `halt` element described in the **4.1.1 The mode section** is basically the equivalent to `final_halt`, as there is no 2nd stage.

Additionally, I think we should remove the following sections:

* **9.4.2 System customization**. Perhaps 9.4.1 content could be included directly in 9.4.
* **4.1.6 The wait section**

2021-05-26 20:13 UTC, imobachgs commented
>     * The `halt` element described in the **4.1.1 The mode section** is basically the equivalent to `final_halt`, as there is no 2nd stage.

I have checked the AutoYaST code and I would say that we should drop the following elements: `final_halt`, `final_reboot`, `final_restart_services`, `activate_systemd_default_target` and `max_systemd_wait`. All those elements are processed during the 2nd stage, so they are basically ignored in MicroOS.

However, we should keep `halt` but removing the reference to the *second stage*. Something like: *Instead of rebooting ~~into stage two~~, the machine is turned off.*

2021-05-26 20:14 UTC, imobachgs requested changes
Sorry, I forgot to post my comments as a review. I hope it helps.

2021-05-26 20:44 UTC, cjschroder commented
Thanks @imobachgs! I believe @lvicoun is going to finish this PR, as she maintains the SLE Micro guide.

2021-05-28 08:31 UTC, closed without merging

2021-05-28 08:32 UTC, lvicoun commented
Reviewers comments applied.