Guest-dedicated Crypto Adapters passthru (jsc#SLE-4578)
SUSE/doc-sle pull request #878
Opened 2021-06-03 13:05 UTC by tbazant

### PR creator: Description

This update describes how to use host's crypto adapters inside guest VM.

### PR creator: Are there any relevant issues/feature requests?

* jsc#SLE-4578
* jsc#DOCTEAM-41

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 SP4/openSUSE Leap 15.4 *(if applicable to 15 SP4 _only_ -- do not merge yet!)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP2/openSUSE Leap 15.2
  - [x] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2021-06-03 13:17 UTC, lproven requested changes

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +  <title>Crypto adapters pass-through to &kvm; guests on &zseries;</title>
```suggestion
  <title>Crypto adapter pass-through to &kvm; guests on &zseries;</title>
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +    for example, random number generation, digital signature generation, or
```suggestion
    &zseries; machines include cryptographic hardware with useful functions
    such as random number generation, digital signature generation, or
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +    pass-through devices while the hypervisor cannot observe the communication
```suggestion
    pass-through devices, in which the hypervisor cannot observe communications
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +      sure it is shut down.
```suggestion
      Either create a new VM (refer to <xref linkend="ha-kvm-inst"/>) and
      wait until it is initialized, or use an existing VM. In both cases, make
      sure the VM is shut down.
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +      Installation of virtualization components is detailed in
```suggestion
      The installation of virtualization components is detailed in
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +      <literal>vfio_ap</literal> architecture is detailed in
```suggestion
      The <literal>vfio_ap</literal> architecture is detailed in
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +      General outline together with a detailed procedure is described in
```suggestion
      A general outline together with a detailed procedure is described in
```

2021-06-03 13:17 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +      The architecture of VFIO Mediated devices (MDEV) is detailed in
```suggestion
      The architecture of VFIO Mediated devices (MDEVs) is detailed in
```

2021-06-04 12:45 UTC, lproven approved these changes

2021-06-07 11:46 UTC, lproven approved these changes

2021-06-09 15:49 UTC, lproven requested changes

2021-06-09 15:49 UTC, lproven commented on xml/libvirt_configuration_virsh.xml
> +    pass-through devices, in which the hypervisor cannot observe communications
```suggestion
    pass-through devices. The means that the hypervisor cannot observe communications
```

2021-06-10 08:49 UTC, tbazant commented on xml/libvirt_configuration_virsh.xml
> +      verify the matrix that you have configured:
```suggestion
      Verify the matrix that you have configured:
```

2021-06-10 13:23 UTC, lproven approved these changes

2021-06-11 11:17 UTC, tbazant commented
> Just one small place: Could you add driver vfio_ap and vfio_mdev to Requirements15.18.3. Move 4 to 1 in 15.18.4 by checking driver with "lsmod | grep vfio_", make sure if vfio_ap and vfio_mdev are loaded, otherwise load them with modprobe.
> 
> I also saw there are a lot of operations with "bash code" here, just wondering if you tested them in our SLE environment? sometimes the output may be different which will confuse our readers.

@liayan i have included your suggestion. and no, i havent tested it

2021-06-11 13:00 UTC, lproven approved these changes

2021-06-14 07:23 UTC, merged