Virt manager cpu fixes
SUSE/doc-sle pull request #935
Opened 2021-08-05 23:47 UTC by jfehlig

### PR creator: Description

Improve the virt-manager CPU and memory sections in the VT guide. virt-manager no longer supports specifying current and maximum number of vCPUs. The doc should be updated to reflect that.

Also add descriptions of the host-model and host-passthrough models since they are commonly used and a source of confusion.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1188299 (see comments 6&7)

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2021-08-09 16:36 UTC, jfehlig commented
Thanks @hw-claudio for the comments. I've fixed the typos and the duplicated commit messages in 4/4. Not sure how I managed to have the same commit message in patches 3 and 4.

2021-08-10 08:34 UTC, tbazant requested changes
Good job! Minor changes only, and... https://github.com/SUSE/doc-sle/pull/932 needs to be merged first in order for the changed link to work

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    <term><guimenu>Logical host CPUs</guimenu></term> shows the number of
```suggestion
    <guimenu>Logical host CPUs</guimenu> shows the number of
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    seen in the output of 'virsh capabilities'. When deactivated, the CPU model
```suggestion
    uses the host CPU model for &vmguest;. You can see the details of the host CPU model in the output of the <command>virsh capabilities</command> command. When deactivated, the CPU model
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    must be specified from the models available in the drop-down box.
```suggestion
    needs to be specified from the models available in the drop-down box.
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    and ability to migrate the &vmguest; &libvirt; does not model every aspect
```suggestion
    and ability to migrate the &vmguest;. &libvirt; does not model every aspect
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    The host-passthrough model is also required in some cases, e.g. when running
```suggestion
    The host-passthrough model is also required in some cases, for example, when running
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    at <link xlink:href="https://libvirt.org/formatdomain.html#cpu-model-and-topology"/>.
```suggestion
   <xref linkend="libvirt-config-virsh-cpu"/>.
```

2021-08-10 08:34 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    the <citetitle>CPU model and topology</citetitle> documentation
```suggestion
    For more information on &libvirt;'s CPU model and topology options, refer to
```

2021-08-10 12:19 UTC, tbazant requested changes
another portion of minor updates

2021-08-10 12:19 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    The host-passthrough model provides the &vmguest; with a CPU that is exactly
```suggestion
    The <literal>host-passthrough</literal> model provides the &vmguest; with a CPU that is exactly
```

2021-08-10 12:19 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    requires CPU features not available in &libvirt;'s simplified host-model CPU.
```suggestion
    requires CPU features not available in &libvirt;'s simplified <literal>host-model</literal> CPU.
```

2021-08-10 12:19 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    The host-passthrough model is also required in some cases, e.g. when running
```suggestion
    The <literal>host-passthrough</literal> model is also required in some cases, for example, when running
```

2021-08-10 12:19 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +    host-passthrough model CPU can only be migrated to a &vmhost; with identical
```suggestion
    &vmguest;s with more than 4TB of memory. The <literal>host-passthrough</literal> model comes
    with the disadvantage of reduced migration capability. A &vmguest; with
    <literal>host-passthrough</literal> model CPU can only be migrated to a &vmhost; with identical
```

2021-08-10 12:19 UTC, tbazant commented on xml/libvirt_configuration_gui.xml
> +      use the host-passthrough CPU model.
```suggestion
      &vmguests; with memory requirements of 4TB or more currently need to
      use the <literal>host-passthrough</literal> CPU model.
```

2021-08-10 17:59 UTC, merged